# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
import sys
sys.path.append('/path/to/directory/containing/initialize.py')


#### 1. Import the numpy package under the name `np` (★☆☆)

In [7]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a=np.zeros((10,10))
print("%d bytes" % (a.size * a.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a=np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a=np.matrix(np.arange(0,9)).reshape(3,3)
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a=np.random.random((3,3,3))
a

array([[[0.16409913, 0.14325476, 0.92926194],
        [0.50222933, 0.95401885, 0.59134043],
        [0.62602911, 0.68146528, 0.17622005]],

       [[0.64317752, 0.12286482, 0.21352531],
        [0.9198167 , 0.21765785, 0.17761097],
        [0.96527229, 0.51893874, 0.84176464]],

       [[0.63682115, 0.97218326, 0.24841754],
        [0.52007779, 0.15482974, 0.87732038],
        [0.79847782, 0.12601334, 0.08225545]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a=np.random.random((10,10))
print(a.min())
print(a.max())

0.009104684731663593
0.9943307357336367


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a=np.random.random(30)
a.mean()

0.49276532559923064

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a=np.ones((10,10))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
a=np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
a=np.unravel_index(100,(6,7,8))
a

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [9]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [8]:
a=np.random.random((5,5))
a=(a-np.mean(a))/np.std(a)
a

array([[-0.86080972, -0.52079073, -0.7517343 , -1.71168585,  1.15552804],
       [ 1.0049758 ,  0.28597766, -1.61163584,  1.08219511,  1.62273412],
       [-0.71590633,  1.59047085, -0.39630817,  1.44426956,  0.67947246],
       [ 0.0027857 , -1.19588463, -0.23247512, -0.86063584, -0.08001109],
       [-1.28660255, -0.66206338,  0.53196017,  1.06320117,  0.4229729 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
a

<ipython-input-10-643e6e996a4a>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
a=np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
a=np.arange(11)
a[(3<a)&(a<=8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
a=sum(range(5),-1)
a

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [14]:
a=np.arange(5)
a**a

array([  1,   1,   4,  27, 256])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
a=np.array(0) / np.array(0)
a

<ipython-input-15-a05e5e65e42f>:1: RuntimeWarning: invalid value encountered in divide
  a=np.array(0) / np.array(0)


nan

#### 29. How to round away from zero a float array ? (★☆☆)

In [16]:
a=np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(a)),a)

array([ -1.,  -3.,  -2., -10.,   1.,  -1.,   1.,   6.,   9.,  -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
a=np.arange(0,10)
b=np.arange(5,15)
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [18]:
a=np.ones(1)/0
np.seterr(all="ignore")
a

<ipython-input-18-1630d4069825>:1: RuntimeWarning: divide by zero encountered in divide
  a=np.ones(1)/0


array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [19]:
a=np.sqrt(-1) == np.emath.sqrt(-1)
a

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [20]:
a=np.datetime64('today')
print(a-np.timedelta64(1))
print(a)
print(a+np.timedelta64(1))

2024-12-01
2024-12-02
2024-12-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [21]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [22]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)

array([-0.5, -0.5, -0.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [23]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[1. 8. 8. 1. 3. 1. 0. 5. 9. 9.]
[1. 8. 8. 1. 3. 1. 0. 5. 9. 9.]
[1. 8. 8. 1. 3. 1. 0. 5. 9. 9.]
[1 8 8 1 3 1 0 5 9 9]
[1. 8. 8. 1. 3. 1. 0. 5. 9. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
a=np.zeros((5,5))
a+=np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [25]:
a=np.random.randint(0,10,10)
a

array([7, 3, 8, 1, 4, 6, 1, 3, 0, 1])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [26]:
a=np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [27]:
a=np.random.random(10)
a.sort()
a

array([0.04425003, 0.06753588, 0.25831361, 0.27350469, 0.30013626,
       0.31133979, 0.48225143, 0.58417947, 0.62948593, 0.68673798])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [28]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [29]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
np.allclose(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [30]:
a=np.zeros(10)
a.flags.writeable=False
a[0]=1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [31]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.9267228  0.88946753 0.29845353 0.95458368 0.72285527 0.98794854
 0.99415413 0.52630841 0.45304654 0.98960896]
[0.67642789 1.40791402 0.03096279 1.30124767 0.53729795 0.56257775
 1.19130977 1.00296812 0.84862125 0.15410683]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [32]:
a=np.random.random(10)
a[a.argmax()]=0
a

array([0.39946144, 0.63778788, 0.00778332, 0.25462528, 0.74448995,
       0.74848709, 0.74738114, 0.4158549 , 0.41885738, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [33]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [34]:
a=np.arange(8)
b=a+0.5
c=1.0/np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [35]:
a=np.array([np.int8,np.int32,np.int64,np.float32,np.float64])
for i in a:
    print

#### 49. How to print all the values of an array? (★★☆)

In [36]:
a=np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [37]:
a=np.arange(100)
b=np.random.uniform(0,100)
index=(np.abs(a-b)).argmin()
print(a[index])

10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [38]:
a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
a

<ipython-input-38-aa173d70e449>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [39]:
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
d

array([[0.        , 0.20232915, 0.86303215, 0.0881872 , 0.89783956,
        0.36562097, 0.5217595 , 0.21339937, 0.01736259, 0.59250155],
       [0.20232915, 0.        , 0.71706197, 0.11414314, 0.82681035,
        0.44855988, 0.32322415, 0.12754149, 0.19797409, 0.3965125 ],
       [0.86303215, 0.71706197, 0.        , 0.79661981, 0.37236275,
        0.7592163 , 0.4888743 , 0.65011645, 0.8696946 , 0.66901626],
       [0.0881872 , 0.11414314, 0.79661981, 0.        , 0.86209575,
        0.391526  , 0.43485939, 0.15099812, 0.08470993, 0.5063842 ],
       [0.89783956, 0.82681035, 0.37236275, 0.86209575, 0.        ,
        0.64503002, 0.73140432, 0.71571845, 0.91048068, 0.93879017],
       [0.36562097, 0.44855988, 0.7592163 , 0.391526  , 0.64503002,
        0.        , 0.64561344, 0.33563179, 0.38287481, 0.80465248],
       [0.5217595 , 0.32322415, 0.4888743 , 0.43485939, 0.73140432,
        0.64561344, 0.        , 0.34520023, 0.51956606, 0.2094478 ],
       [0.21339937, 0.12754149, 0.6501164

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [40]:
a=np.arange(10,dtype=np.float32)
a=a.astype(np.int32,copy=False)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [41]:
a=np.genfromtxt("missing.dat",delimiter=",")
a

FileNotFoundError: missing.dat not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [42]:
a=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(a):
    print(index,value)
for index in np.ndindex(a.shape):
    print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [43]:
a=np.random.random((5,5))

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [44]:
a=np.zeros((5,5))
np.put(a,np.random.choice(range(5*5),5,replace=False),1)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [45]:
a=np.random.rand(5,10)
b=a-a.mean(axis=1,keepdims=True)
b

array([[ 0.40422438,  0.42789072, -0.33393665, -0.07392921, -0.23910073,
        -0.3329978 ,  0.40890615,  0.2407561 , -0.28589144, -0.21592151],
       [-0.30014357, -0.11856472, -0.320293  , -0.12951307,  0.3679547 ,
         0.3776956 , -0.22949669, -0.30864155,  0.46099743,  0.20000488],
       [ 0.42060447,  0.23389786, -0.22910649, -0.12937398, -0.32646915,
        -0.14476093,  0.33801897, -0.34154204,  0.36559292, -0.18686163],
       [ 0.15935764, -0.07519963,  0.42866019, -0.11762217,  0.45394724,
        -0.05828785, -0.1325442 , -0.15026909, -0.26248154, -0.24556057],
       [-0.33956859, -0.32505323, -0.24140962,  0.44541468, -0.09435796,
         0.16416702,  0.40583624,  0.30097931,  0.0752605 , -0.39126834]])

#### 59. How to sort an array by the nth column? (★★☆)

In [46]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[4 8 5]
 [7 9 3]
 [0 0 1]]
[[0 0 1]
 [4 8 5]
 [7 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [47]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [48]:
a=np.random.uniform(0,1,10)
b=0.5
c=a.flat[np.abs(a-b).argmin()]
c

0.5322876801476524

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [49]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it:
    z[...]=x+y

#### 63. Create an array class that has a name attribute (★★☆)

In [50]:
a=np.zeros(10)
a.flags.writeable=False
a[0]=1

ValueError: assignment destination is read-only

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [51]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
a+=np.bincount(b,minlength=len(a))
a

array([2., 2., 2., 5., 2., 5., 2., 2., 4., 4.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [52]:
a=[1,2,3,4,5,6]
b=[1,3,9,3,4,1]
c=np.bincount(b,a)
c

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [53]:
a=np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
f=a[...,0]*(256*256)+a[...,1]*256+a[...,2]
print(len(np.unique(f)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [54]:
a=np.random.randint(0,10,(3,4,3,4))
sum=a.reshape(a.shape[:-2]+(-1,)).sum(axis=-1)
print(sum)

[[43 39 63 61]
 [58 49 44 55]
 [47 42 54 74]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [55]:
a=np.random.uniform(0,1,100)
b=np.random.randint(0,10,100)
d_sums=np.bincount(b,weights=a)
d_counts=np.bincount(b)

#### 69. How to get the diagonal of a dot product? (★★★)

In [56]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))

array([2.08740505, 0.52194018, 0.99927474, 1.21935756, 1.58885494])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [57]:
a=np.array([1,2,3,4,5])
b=3
c=np.zeros(len(a)+(len(a)-1)*(b))
c[::b+1]=a

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [58]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [59]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [63]:
a=np.random.randint(0,100,(10,3))
b=np.roll(a.repeat(2,axis=1),-1,axis=1)
b=b.reshape(len(b)*3,2)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [62]:
a=np.bincount([1,1,2,3,4,4,6])
b=np.repeat(np.arange(len(a)),a)
b

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [64]:
a=np.arange(20)
b=3
c=np.cumsum(a,dtype=float)
c[b:] = c[b:] - c[:-b]
c[b-1:]/b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [65]:
a=np.arange(10)
b=3
c=a.reshape(len(a)-b+1,b)
c

ValueError: cannot reshape array of size 10 into shape (8,3)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [67]:
a=np.random.randint(0,2,100)
np.logical_not(a,out=a)
a=np.random.uniform(-1.0,1.0,100)
np.negative(a,out=a)

array([ 0.14148336,  0.15237491,  0.52328175, -0.23949267, -0.23633622,
        0.76470297,  0.29649296,  0.18199031,  0.70900946,  0.29480351,
        0.13189684,  0.08449218,  0.08912869, -0.11586377,  0.2057653 ,
        0.41551816,  0.94240663, -0.17336082,  0.7750323 ,  0.00263756,
       -0.37474787, -0.91745915, -0.70989758,  0.63501425, -0.82360951,
        0.44350919, -0.16237618, -0.69407083,  0.07606529, -0.40750254,
       -0.35306824, -0.83388996, -0.38683134, -0.58590941, -0.61178728,
       -0.99257252, -0.95142666,  0.91014996, -0.05757691, -0.2458775 ,
       -0.64929004, -0.23197622,  0.2715714 , -0.83015523, -0.80322912,
        0.97662331,  0.64297493, -0.55081124,  0.63823807,  0.45416814,
       -0.58008774,  0.78270403,  0.84917716,  0.70565416, -0.52733305,
        0.69651496,  0.96671733,  0.3231012 ,  0.48700349, -0.0526046 ,
       -0.0799051 ,  0.22017018,  0.01852236,  0.74228289,  0.10129879,
        0.45859278,  0.75056059, -0.6502288 , -0.48134802, -0.36

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [68]:
a=np.random.uniform(-10,10,(10,2))
b=np.random.uniform(-10,10,(1,2))
c=np.dtype([('p0',float),('p1',float)])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [69]:
a=np.random.uniform(-10,10,(10,2))
b=np.random.uniform(-10,10,(10,2))
c=np.random.uniform(-10,10,(10,2))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [70]:
a=np.random.randint(0,10,(10,10))
b=np.random.randint(0,10,(3,3))

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [71]:
a=np.arange(1,15,dtype=np.uint32)
b=np.lib.stride_tricks.as_strided(a,(11,4),(4,4))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [72]:
a=np.random.uniform(0,1,(10,10))
u,s,v=np.linalg.svd(a)
rank=np.sum(s>1e-10)
rank

10

#### 83. How to find the most frequent value in an array?

In [73]:
a=np.random.randint(0,10,50)
np.bincount(a).argmax()

3

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [74]:
a=np.random.randint(0,5,(10,10))

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [75]:
a=np.random.randint(0,5,(5,5))

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [76]:
a=np.ones((16,16))
b=np.ones((16,1))
c=np.ones(16)*1

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [77]:
a=np.ones((16,16))

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [78]:
a=np.random.randint(0,2,(5,5))

#### 89. How to get the n largest values of an array (★★★)

In [79]:
a=np.arange(10000)
np.random.shuffle(a)
n=5
print(a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [80]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))

#### 91. How to create a record array from a regular array? (★★★)

In [81]:
a=np.array([("Hello", 2.5, 3),("World", 3.6, 2)])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [82]:
a=np.random.rand(5)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [83]:
a=np.random.randint(0,5,(8,3))
b=np.random.randint(0,5,(2,2))

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [84]:
a=np.random.randint(0,5,(10,3))

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [85]:
a=np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(a[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [86]:
a=np.random.randint(0,2,(6,3))

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [87]:
a=np.random.uniform(0,1,10)
b=np.random.uniform(0,1,10)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [91]:
a=np.arange(0,16).reshape(4,4)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [90]:
a=np.asarray([[1.0, 0.0, 0.0, 0.0]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [89]:
a=np.random.randn(100)
n=1000
idx=np.random.randint(0,a.size,(n,a.size))
means=a[idx].mean(axis=1)